CREATE SCHEMA IF NOT EXISTS sarf;

-- =============================================
-- USERS TABLE
-- account_number is the PRIMARY KEY (6 digits, generated by function below)
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.users (
    account_number         VARCHAR(6)   PRIMARY KEY,
    first_name             VARCHAR(100) NOT NULL,
    last_name              VARCHAR(100) NOT NULL,
    date_of_birth          DATE         NOT NULL,
    gender                 VARCHAR(10)  NOT NULL CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    email                  VARCHAR(255),
    country_code           VARCHAR(5),
    phone_number           VARCHAR(15),
    password_hash          VARCHAR(255),
    google_id              VARCHAR(255),
    registration_type      VARCHAR(10)  NOT NULL CHECK (registration_type IN ('PHONE', 'GOOGLE')),
    registration_date_time TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE (country_code, phone_number),
    UNIQUE (email),
    UNIQUE (google_id)
);

-- =============================================
-- OTP RECORDS TABLE
-- Stores only the OTP code for a given phone.
-- No registration data that arrives later in /register.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.otp_records (
    id                     BIGSERIAL   PRIMARY KEY,
    country_code           VARCHAR(5)  NOT NULL,
    phone_number           VARCHAR(15) NOT NULL,
    otp_code               VARCHAR(64) NOT NULL,
    expires_at             TIMESTAMP   NOT NULL,
    used                   BOOLEAN     NOT NULL DEFAULT FALSE,
    registration_date_time TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_otp_phone
    ON sarf.otp_records (country_code, phone_number, used, expires_at);

-- =============================================
-- REGISTRATION SESSIONS TABLE
-- Short-lived token issued after OTP is confirmed.
-- Required to call /registration/submit.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.registration_sessions (
    id            BIGSERIAL   PRIMARY KEY,
    session_token VARCHAR(64) NOT NULL UNIQUE,
    country_code  VARCHAR(5)  NOT NULL,
    phone_number  VARCHAR(15) NOT NULL,
    expires_at    TIMESTAMP   NOT NULL,
    used          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- =============================================
-- LOGIN AUDIT TABLE
-- Records every login attempt (success and failure).
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.login_audit (
    id                BIGSERIAL   PRIMARY KEY,
    account_number    VARCHAR(6)  REFERENCES sarf.users(account_number),
    device_id         VARCHAR(255),
    response_code     VARCHAR(10) NOT NULL,
    registration_type VARCHAR(10),
    login_date_time   TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_login_audit_device
    ON sarf.login_audit (device_id, login_date_time);

CREATE INDEX IF NOT EXISTS idx_login_audit_account
    ON sarf.login_audit (account_number, login_date_time);

-- =============================================
-- USER DEVICES TABLE
-- Stores known devices per account.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.user_devices (
    id             BIGSERIAL    PRIMARY KEY,
    account_number VARCHAR(6)   NOT NULL REFERENCES sarf.users(account_number),
    device_id      VARCHAR(64)  NOT NULL,
    device_name    VARCHAR(150),
    fcm_token      VARCHAR(512),
    first_seen_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    last_seen_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_devices_account_device UNIQUE (account_number, device_id)
);

CREATE INDEX IF NOT EXISTS idx_user_devices_account
    ON sarf.user_devices (account_number);

-- =============================================
-- CURRENCIES TABLE
-- Master list of supported fiat and metals.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.currencies (
    code          VARCHAR(10)  PRIMARY KEY,
    name_en       VARCHAR(100) NOT NULL,
    name_ar       VARCHAR(100) NOT NULL,
    symbol        VARCHAR(20),
    country_code  VARCHAR(5),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    is_metal      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

INSERT INTO sarf.currencies (
    code, name_en, name_ar, symbol, country_code, active, display_order, is_metal
) VALUES
    ('USD', 'US Dollar', 'الدولار الأمريكي', '$', '1', TRUE, 1, FALSE),
    ('EUR', 'Euro', 'اليورو', 'EUR', NULL, TRUE, 2, FALSE),
    ('SAR', 'Saudi Riyal', 'الريال السعودي', 'SAR', '966', TRUE, 3, FALSE),
    ('AED', 'UAE Dirham', 'الدرهم الإماراتي', 'AED', '971', TRUE, 4, FALSE),
    ('EGP', 'Egyptian Pound', 'الجنيه المصري', 'EGP', '20', TRUE, 5, FALSE),
    ('SDG', 'Sudanese Pound', 'الجنيه السوداني', 'SDG', '249', TRUE, 6, FALSE),
    ('QAR', 'Qatari Riyal', 'الريال القطري', 'QAR', '974', TRUE, 7, FALSE),
    ('KWD', 'Kuwaiti Dinar', 'الدينار الكويتي', 'KWD', '965', TRUE, 8, FALSE),
    ('BHD', 'Bahraini Dinar', 'الدينار البحريني', 'BHD', '973', TRUE, 9, FALSE),
    ('OMR', 'Omani Rial', 'الريال العماني', 'OMR', '968', TRUE, 10, FALSE),
    ('JOD', 'Jordanian Dinar', 'الدينار الأردني', 'JOD', '962', TRUE, 11, FALSE),
    ('GBP', 'British Pound', 'الجنيه الإسترليني', 'GBP', '44', TRUE, 12, FALSE),
    ('TRY', 'Turkish Lira', 'الليرة التركية', 'TRY', '90', TRUE, 13, FALSE),
    ('CNY', 'Chinese Yuan', 'اليوان الصيني', 'CNY', '86', TRUE, 14, FALSE),
    ('XAU', 'Gold', 'الذهب', 'Au', NULL, TRUE, 15, TRUE),
    ('XAG', 'Silver', 'الفضة', 'Ag', NULL, TRUE, 16, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    symbol = EXCLUDED.symbol,
    country_code = EXCLUDED.country_code,
    active = EXCLUDED.active,
    display_order = EXCLUDED.display_order,
    is_metal = EXCLUDED.is_metal,
    updated_at = NOW();

-- =============================================
-- PRICE HISTORY TABLE
-- Historical rates snapshots.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.price_history (
    id            BIGSERIAL      PRIMARY KEY,
    source        VARCHAR(50)    NOT NULL,
    currency_code VARCHAR(10)    NOT NULL REFERENCES sarf.currencies(code),
    price         NUMERIC(18, 6) NOT NULL,
    tran_date     DATE           NOT NULL DEFAULT CURRENT_DATE,
    tran_time     TIME           NOT NULL DEFAULT CURRENT_TIME
);

CREATE INDEX IF NOT EXISTS idx_price_history_source
    ON sarf.price_history (source);

CREATE INDEX IF NOT EXISTS idx_price_history_currency
    ON sarf.price_history (currency_code);

CREATE INDEX IF NOT EXISTS idx_price_history_date
    ON sarf.price_history (tran_date);

CREATE INDEX IF NOT EXISTS idx_price_history_source_currency_date_time
    ON sarf.price_history (source, currency_code, tran_date, tran_time);

-- =============================================
-- TRANSFER SERVICES
-- Dynamic list of app services.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.services (
    code                   VARCHAR(50)  PRIMARY KEY,
    name_en                VARCHAR(100) NOT NULL,
    name_ar                VARCHAR(100) NOT NULL,
    description_en         VARCHAR(255),
    description_ar         VARCHAR(255),
    logo_url               VARCHAR(500),
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order          INTEGER      NOT NULL DEFAULT 0
);

INSERT INTO sarf.services (
    code, name_en, name_ar, description_en, description_ar, logo_url,
     active, display_order
) VALUES
    ('currency_conversion', 'Currency Conversion', 'تحويل العملات',
     'Legacy catalog service for currency conversion.', 'خدمة قديمة لعرض تحويل العملات.',
     'https://cdn.example.com/services/currency-conversion.png',
      FALSE, 1),
    ('local_transfer', 'Internal Transfer', 'تحويلات محلية',
     'Manual transfers between supported Sudanese banks and wallets.',
     'تحويلات يدوية بين البنوك والمحافظ السودانية المدعومة.',
     'https://cdn.example.com/services/local-transfer.png',
    TRUE, 2),
    ('international_transfer', 'International Transfer', 'تحويلات دولية',
     'Incoming remittance payout requests through exchange houses.',
     'طلبات استلام حوالات واردة عبر دور الصرافة.',
     'https://cdn.example.com/services/international-transfer.png',
      3)

-- =============================================
-- TRANSFER METHODS
-- Banks, wallets, and payout methods used by internal transfer
-- and as local receive methods for international payout.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.transfer_methods (
    id               BIGSERIAL    PRIMARY KEY,
    code             VARCHAR(50)  NOT NULL UNIQUE,
    category         VARCHAR(30)  NOT NULL CHECK (category IN ('BANK', 'WALLET', 'CASH', 'OTHER')),
    name_en          VARCHAR(100) NOT NULL,
    name_ar          VARCHAR(100) NOT NULL,
    short_name       VARCHAR(50),
    currency_code    VARCHAR(10)  NOT NULL REFERENCES sarf.currencies(code),
    logo_url         VARCHAR(500),
    instructions_en  VARCHAR(255),
    instructions_ar  VARCHAR(255),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order    INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);

INSERT INTO sarf.transfer_methods (
    code, category, name_en, name_ar, short_name, currency_code,
    logo_url, instructions_en, instructions_ar, active, display_order
) VALUES
    ('bankak', 'BANK', 'Bank of Khartoum', 'بنك الخرطوم', 'Bankak', 'SDG',
     'https://cdn.example.com/methods/bankak.png',
     'Use your Bankak account for manual payment.', 'استخدم حساب بنك الخرطوم للدفع اليدوي.', TRUE, 1),
    ('faisal_bank', 'BANK', 'Faisal Islamic Bank', 'بنك فيصل الإسلامي', 'Faisal', 'SDG',
     'https://cdn.example.com/methods/faisal-bank.png',
     'Use your Faisal account for manual payment.', 'استخدم حساب فيصل للدفع اليدوي.', TRUE, 2),
    ('onb_bank', 'BANK', 'Omdurman National Bank', 'بنك أم درمان الوطني', 'ONB', 'SDG',
     'https://cdn.example.com/methods/onb-bank.png',
     'Use your ONB account for manual payment.', 'استخدم حساب أم درمان الوطني للدفع اليدوي.', TRUE, 3),
    ('mycash_wallet', 'WALLET', 'MyCashi Wallet', 'محفظة ماي كاشي', 'MyCashi', 'SDG',
     'https://cdn.example.com/methods/mycash-wallet.png',
     'Use your wallet balance for manual payment.', 'استخدم رصيد المحفظة للدفع اليدوي.', TRUE, 4),
    ('bravo', 'WALLET', 'Bravo Wallet', 'محفظة برافو', 'Bravo', 'SDG',
     'https://cdn.example.com/methods/bravo-wallet.png',
     'Use your wallet balance for manual payment.', 'استخدم رصيد المحفظة للدفع اليدوي.', TRUE, 5),
    ('bank_transfer', 'BANK', 'Bank Transfer', 'تحويل بنكي', 'Bank', 'SDG',
     'https://cdn.example.com/methods/bank-transfer.png',
     'Recipient receives by bank transfer.', 'يستلم المستفيد بتحويل بنكي.', TRUE, 10),
    ('mobile_wallet', 'WALLET', 'Mobile Wallet', 'محفظة إلكترونية', 'Wallet', 'SDG',
     'https://cdn.example.com/methods/mobile-wallet.png',
     'Recipient receives by mobile wallet.', 'يستلم المستفيد عبر المحفظة الإلكترونية.', TRUE, 11)
ON CONFLICT (code) DO UPDATE SET
    category = EXCLUDED.category,
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    short_name = EXCLUDED.short_name,
    currency_code = EXCLUDED.currency_code,
    logo_url = EXCLUDED.logo_url,
    instructions_en = EXCLUDED.instructions_en,
    instructions_ar = EXCLUDED.instructions_ar,
    active = EXCLUDED.active,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

-- =============================================
-- MERCHANTS
-- Manual operators for internal transfer fulfillment.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.merchants (
    id            BIGSERIAL    PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL UNIQUE,
    name_en       VARCHAR(100) NOT NULL,
    name_ar       VARCHAR(100) NOT NULL,
    phone_number  VARCHAR(20),
    logo_url      VARCHAR(500),
    notes_en      VARCHAR(500),
    notes_ar      VARCHAR(500),
    rating        NUMERIC(3, 2),
    eta_min_min   INTEGER,
    eta_max_min   INTEGER,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

INSERT INTO sarf.merchants (
    code, name_en, name_ar, phone_number, logo_url, notes_en, notes_ar,
    rating, eta_min_min, eta_max_min, active
) VALUES
    ('merchant_rahma', 'Rahma', 'رحمة', '249000000001',
     'https://cdn.example.com/merchants/rahma.png',
     'Primary merchant for internal transfers.', 'تاجر أساسي للتحويلات المحلية.',
     4.80, 3, 8, TRUE),
    ('merchant_sondos', 'Sondos', 'سندس', '249000000002',
     'https://cdn.example.com/merchants/sondos.png',
     'Fast review merchant.', 'تاجر سريع في المراجعة.',
     4.90, 5, 10, TRUE),
    ('merchant_moez', 'Moez', 'معز', '249000000003',
     'https://cdn.example.com/merchants/moez.png',
     'Handles larger transfers.', 'يتعامل مع الحوالات الأكبر.',
     4.70, 10, 20, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    phone_number = EXCLUDED.phone_number,
    logo_url = EXCLUDED.logo_url,
    notes_en = EXCLUDED.notes_en,
    notes_ar = EXCLUDED.notes_ar,
    rating = EXCLUDED.rating,
    eta_min_min = EXCLUDED.eta_min_min,
    eta_max_min = EXCLUDED.eta_max_min,
    active = EXCLUDED.active,
    updated_at = NOW();

-- =============================================
-- MERCHANT RECEIVING ACCOUNTS
-- Account details shown to the user in internal transfer flows.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.merchant_accounts (
    id                 BIGSERIAL    PRIMARY KEY,
    merchant_id        BIGINT       NOT NULL REFERENCES sarf.merchants(id),
    transfer_method_id BIGINT       NOT NULL REFERENCES sarf.transfer_methods(id),
    account_name       VARCHAR(150) NOT NULL,
    account_number     VARCHAR(100),
    iban               VARCHAR(100),
    wallet_number      VARCHAR(50),
    bank_name          VARCHAR(100),
    instructions_en    VARCHAR(500),
    instructions_ar    VARCHAR(500),
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_merchant_method_account UNIQUE (merchant_id, transfer_method_id)
);

CREATE INDEX IF NOT EXISTS idx_merchant_accounts_merchant_method
    ON sarf.merchant_accounts (merchant_id, transfer_method_id, active);

INSERT INTO sarf.merchant_accounts (
    merchant_id, transfer_method_id, account_name, account_number, iban,
    wallet_number, bank_name, instructions_en, instructions_ar, active
)
SELECT
    m.id,
    tm.id,
    CASE m.code
        WHEN 'merchant_rahma' THEN 'Rahma Sarf'
        WHEN 'merchant_sondos' THEN 'Sondos Exchange'
        WHEN 'merchant_moez' THEN 'Moez Transfer'
    END,
    CASE tm.code
        WHEN 'bankak' THEN CASE m.code WHEN 'merchant_rahma' THEN '0912345678' WHEN 'merchant_sondos' THEN '0922233344' ELSE '0933300044' END
        WHEN 'faisal_bank' THEN CASE m.code WHEN 'merchant_rahma' THEN '220011445566' WHEN 'merchant_sondos' THEN '220011998877' ELSE '110022334455' END
        WHEN 'onb_bank' THEN CASE m.code WHEN 'merchant_rahma' THEN '998877665544' WHEN 'merchant_sondos' THEN '776655443322' ELSE '554433221100' END
        ELSE NULL
    END,
    NULL,
    CASE tm.code
        WHEN 'mycash_wallet' THEN CASE m.code WHEN 'merchant_rahma' THEN '0998877665' WHEN 'merchant_sondos' THEN '0990011223' ELSE '0994455667' END
        WHEN 'bravo' THEN CASE m.code WHEN 'merchant_rahma' THEN '0998877665' WHEN 'merchant_sondos' THEN '0990011223' ELSE '0994455667' END
        ELSE NULL
    END,
    CASE tm.category
        WHEN 'BANK' THEN tm.name_en
        ELSE tm.name_en
    END,
    'Transfer exactly the quoted amount and upload your receipt.',
    'حوّل المبلغ المطابق للعرض ثم ارفع الإيصال.',
    TRUE
FROM sarf.merchants m
JOIN sarf.transfer_methods tm
  ON tm.code IN ('bankak', 'faisal_bank', 'onb_bank', 'mycash_wallet', 'bravo')
ON CONFLICT (merchant_id, transfer_method_id) DO UPDATE SET
    account_name = EXCLUDED.account_name,
    account_number = EXCLUDED.account_number,
    wallet_number = EXCLUDED.wallet_number,
    bank_name = EXCLUDED.bank_name,
    instructions_en = EXCLUDED.instructions_en,
    instructions_ar = EXCLUDED.instructions_ar,
    active = EXCLUDED.active,
    updated_at = NOW();

-- =============================================
-- INTERNAL TRANSFER ROUTES
-- Defines allowed source -> target pairs for local transfer.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.internal_transfer_routes (
    id                 BIGSERIAL      PRIMARY KEY,
    source_method_id   BIGINT         NOT NULL REFERENCES sarf.transfer_methods(id),
    target_method_id   BIGINT         NOT NULL REFERENCES sarf.transfer_methods(id),
    rate               NUMERIC(18, 6) NOT NULL DEFAULT 1.0,
    min_amount         NUMERIC(18, 2),
    max_amount         NUMERIC(18, 2),
    active             BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP      NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_internal_transfer_route UNIQUE (source_method_id, target_method_id),
    CONSTRAINT chk_internal_route_diff CHECK (source_method_id <> target_method_id)
);

CREATE INDEX IF NOT EXISTS idx_internal_transfer_routes_active
    ON sarf.internal_transfer_routes (source_method_id, active);

INSERT INTO sarf.internal_transfer_routes (
    source_method_id, target_method_id, rate, min_amount, max_amount, active
)
SELECT
    src.id,
    dst.id,
    1.0,
    100.00,
    10000000.00,
    TRUE
FROM sarf.transfer_methods src
JOIN sarf.transfer_methods dst
  ON (src.code, dst.code) IN (
      ('bankak', 'faisal_bank'),
      ('bankak', 'onb_bank'),
      ('faisal_bank', 'bankak'),
      ('faisal_bank', 'mycash_wallet'),
      ('faisal_bank', 'bravo'),
      ('onb_bank', 'bankak'),
      ('mycash_wallet', 'onb_bank'),
      ('bravo', 'onb_bank')
  )
ON CONFLICT (source_method_id, target_method_id) DO UPDATE SET
    rate = EXCLUDED.rate,
    min_amount = EXCLUDED.min_amount,
    max_amount = EXCLUDED.max_amount,
    active = EXCLUDED.active,
    updated_at = NOW();

-- =============================================
-- MERCHANT ROUTE SUPPORT
-- Which merchant can fulfill which internal route.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.merchant_route_support (
    id                 BIGSERIAL   PRIMARY KEY,
    merchant_id        BIGINT      NOT NULL REFERENCES sarf.merchants(id),
    route_id           BIGINT      NOT NULL REFERENCES sarf.internal_transfer_routes(id),
    min_amount         NUMERIC(18, 2),
    max_amount         NUMERIC(18, 2),
    active             BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_merchant_route_support UNIQUE (merchant_id, route_id)
);

CREATE INDEX IF NOT EXISTS idx_merchant_route_support_active
    ON sarf.merchant_route_support (route_id, active);

INSERT INTO sarf.merchant_route_support (
    merchant_id, route_id, min_amount, max_amount, active
)
SELECT
    m.id,
    r.id,
    100.00,
    10000000.00,
    TRUE
FROM sarf.merchants m
CROSS JOIN sarf.internal_transfer_routes r
ON CONFLICT (merchant_id, route_id) DO UPDATE SET
    min_amount = EXCLUDED.min_amount,
    max_amount = EXCLUDED.max_amount,
    active = EXCLUDED.active,
    updated_at = NOW();

-- =============================================
-- MERCHANT FEE CONFIGS
-- Configurable globally or per internal route.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.merchant_fee_configs (
    id           BIGSERIAL      PRIMARY KEY,
    merchant_id  BIGINT         NOT NULL REFERENCES sarf.merchants(id),
    service_code VARCHAR(50)    NOT NULL REFERENCES sarf.transfer_services(code),
    route_id     BIGINT         REFERENCES sarf.internal_transfer_routes(id),
    fee_type     VARCHAR(20)    NOT NULL CHECK (fee_type IN ('FIXED', 'PERCENTAGE')),
    fee_value    NUMERIC(18, 4) NOT NULL,
    min_fee      NUMERIC(18, 2),
    max_fee      NUMERIC(18, 2),
    active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_merchant_fee_configs_lookup
    ON sarf.merchant_fee_configs (merchant_id, service_code, route_id, active);

CREATE UNIQUE INDEX IF NOT EXISTS uq_merchant_fee_config_route
    ON sarf.merchant_fee_configs (merchant_id, service_code, route_id)
    WHERE route_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_merchant_fee_config_global
    ON sarf.merchant_fee_configs (merchant_id, service_code)
    WHERE route_id IS NULL;

INSERT INTO sarf.merchant_fee_configs (
    merchant_id, service_code, route_id, fee_type, fee_value, min_fee, max_fee, active
)
SELECT
    m.id,
    'local_transfer',
    NULL,
    'PERCENTAGE',
    CASE m.code
        WHEN 'merchant_rahma' THEN 1.50
        WHEN 'merchant_sondos' THEN 1.20
        WHEN 'merchant_moez' THEN 1.80
    END,
    NULL,
    NULL,
    TRUE
FROM sarf.merchants m
WHERE NOT EXISTS (
    SELECT 1
    FROM sarf.merchant_fee_configs fc
    WHERE fc.merchant_id = m.id
      AND fc.service_code = 'local_transfer'
      AND fc.route_id IS NULL
);

-- =============================================
-- EXCHANGE HOUSES
-- Partner payout desks for international transfer.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.exchange_houses (
    id            BIGSERIAL    PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL UNIQUE,
    name_en       VARCHAR(100) NOT NULL,
    name_ar       VARCHAR(100) NOT NULL,
    logo_url      VARCHAR(500),
    notes_en      VARCHAR(500),
    notes_ar      VARCHAR(500),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

INSERT INTO sarf.exchange_houses (
    code, name_en, name_ar, logo_url, notes_en, notes_ar, active, display_order
) VALUES
    ('mig', 'MIG Exchange', 'صرافة MIG',
     'https://cdn.example.com/exchanges/mig.png',
     NULL, NULL, TRUE, 1)
ON CONFLICT (code) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    logo_url = EXCLUDED.logo_url,
    notes_en = EXCLUDED.notes_en,
    notes_ar = EXCLUDED.notes_ar,
    active = EXCLUDED.active,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

-- =============================================
-- TRANSFER PROVIDERS
-- External remittance providers.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.transfer_providers (
    id            BIGSERIAL    PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL UNIQUE,
    name_en       VARCHAR(100) NOT NULL,
    name_ar       VARCHAR(100) NOT NULL,
    logo_url      VARCHAR(500),
    notes_en      VARCHAR(500),
    notes_ar      VARCHAR(500),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

INSERT INTO sarf.transfer_providers (
    code, name_en, name_ar, logo_url, notes_en, notes_ar, active, display_order
) VALUES
    ('wistron_transfer', 'Wistron Transfer', 'ويسترون ترانسفير',
     'https://play-lh.googleusercontent.com/WEI7',
     'Wistron reference number is required for all transfers.',
     'رقم مرجع ويسترون مطلوب لجميع الحوالات.',
     TRUE, 1),
    ('moneygram', 'MoneyGram', 'موني جرام',
     'https://play-lh.googleusercontent.com/uoo6Vd556jKBapSQyJUcZHxlDANJkH9ddMleB-7cKBUMmAA5iZ5FB6-V7st0putVXHReopMAxtzg8rw-8266CXo=w240-h480-rw',
     'No reference number is needed for MoneyGram transfers.',
     'لا يلزم رقم مرجع لحوالات موني جرام.',
     TRUE, 2)
ON CONFLICT (code) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    logo_url = EXCLUDED.logo_url,
    notes_en = EXCLUDED.notes_en,
    notes_ar = EXCLUDED.notes_ar,
    active = EXCLUDED.active,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

-- =============================================
-- EXCHANGE / PROVIDER SUPPORT
-- Which providers are supported by each exchange house.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.exchange_provider_support (
    id                BIGSERIAL  PRIMARY KEY,
    exchange_house_id BIGINT     NOT NULL REFERENCES sarf.exchange_houses(id),
    provider_id       BIGINT     NOT NULL REFERENCES sarf.transfer_providers(id),
    active            BOOLEAN    NOT NULL DEFAULT TRUE,
    display_order     INTEGER    NOT NULL DEFAULT 0,
    created_at        TIMESTAMP  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_exchange_provider_support UNIQUE (exchange_house_id, provider_id)
);

INSERT INTO sarf.exchange_provider_support (
    exchange_house_id, provider_id, active, display_order
)
SELECT
    eh.id,
    tp.id,
    TRUE,
    tp.display_order
FROM sarf.exchange_houses eh
JOIN sarf.transfer_providers tp
  ON tp.code IN ('wistron_transfer', 'moneygram')
WHERE eh.code = 'mig'
ON CONFLICT (exchange_house_id, provider_id) DO UPDATE SET
    active = EXCLUDED.active,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

-- =============================================
-- PROVIDER REFERENCE RULES
-- Reference input is provider-specific and can be required or optional.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.provider_reference_rules (
    id                         BIGSERIAL    PRIMARY KEY,
    exchange_provider_id       BIGINT       NOT NULL REFERENCES sarf.exchange_provider_support(id),
    required                   BOOLEAN      NOT NULL DEFAULT TRUE,
    field_label_en             VARCHAR(100) NOT NULL DEFAULT 'Reference number',
    field_label_ar             VARCHAR(100) NOT NULL DEFAULT 'رقم المرجع',
    validation_regex           VARCHAR(255),
    help_text_en               VARCHAR(255),
    help_text_ar               VARCHAR(255),
    created_at                 TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at                 TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_provider_reference_rule UNIQUE (exchange_provider_id)
);

INSERT INTO sarf.provider_reference_rules (
    exchange_provider_id, required, field_label_en, field_label_ar,
    validation_regex, help_text_en, help_text_ar
)
SELECT
    eps.id,
    CASE tp.code WHEN 'wistron_transfer' THEN TRUE ELSE FALSE END,
    'Reference number',
    'رقم المرجع',
    NULL,
    CASE tp.code
        WHEN 'wistron_transfer' THEN 'Enter the transfer reference from Wistron.'
        ELSE 'Reference is optional for this provider.'
    END,
    CASE tp.code
        WHEN 'wistron_transfer' THEN 'أدخل رقم مرجع التحويل من ويسترون.'
        ELSE 'المرجع اختياري لهذا المزود.'
    END
FROM sarf.exchange_provider_support eps
JOIN sarf.transfer_providers tp ON tp.id = eps.provider_id
JOIN sarf.exchange_houses eh ON eh.id = eps.exchange_house_id
WHERE eh.code = 'mig'
ON CONFLICT (exchange_provider_id) DO UPDATE SET
    required = EXCLUDED.required,
    field_label_en = EXCLUDED.field_label_en,
    field_label_ar = EXCLUDED.field_label_ar,
    validation_regex = EXCLUDED.validation_regex,
    help_text_en = EXCLUDED.help_text_en,
    help_text_ar = EXCLUDED.help_text_ar,
    updated_at = NOW();

-- =============================================
-- EXCHANGE PROVIDER RATES
-- Provider-specific rates by exchange and source currency.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.exchange_provider_rates (
    id                    BIGSERIAL      PRIMARY KEY,
    exchange_provider_id  BIGINT         NOT NULL REFERENCES sarf.exchange_provider_support(id),
    send_currency_code    VARCHAR(10)    NOT NULL REFERENCES sarf.currencies(code),
    receive_currency_code VARCHAR(10)    NOT NULL REFERENCES sarf.currencies(code),
    rate                  NUMERIC(18, 6) NOT NULL,
    fee_type              VARCHAR(20)    CHECK (fee_type IN ('FIXED', 'PERCENTAGE')),
    fee_value             NUMERIC(18, 4),
    min_amount            NUMERIC(18, 2),
    max_amount            NUMERIC(18, 2),
    note_en               VARCHAR(255),
    note_ar               VARCHAR(255),
    active                BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP      NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_exchange_provider_rate UNIQUE (exchange_provider_id, send_currency_code, receive_currency_code)
);

INSERT INTO sarf.exchange_provider_rates (
    exchange_provider_id, send_currency_code, receive_currency_code, rate,
    fee_type, fee_value, min_amount, max_amount, note_en, note_ar, active
)
SELECT
    eps.id,
    rate_data.send_currency_code,
    'SDG',
    rate_data.rate,
    NULL,
    NULL,
    1.00,
    1000000.00,
    rate_data.note_en,
    rate_data.note_ar,
    TRUE
FROM sarf.exchange_provider_support eps
JOIN sarf.transfer_providers tp ON tp.id = eps.provider_id
JOIN sarf.exchange_houses eh ON eh.id = eps.exchange_house_id
JOIN (
    VALUES
        ('wistron_transfer', 'USD', 2488.00::NUMERIC, NULL::VARCHAR, NULL::VARCHAR),
        ('wistron_transfer', 'SAR', 663.50::NUMERIC, 'Rates are updated daily at 12 PM UTC.', 'يتم تحديث الأسعار يومياً الساعة 12 ظهراً بتوقيت UTC.'),
        ('moneygram', 'USD', 2480.00::NUMERIC, NULL::VARCHAR, NULL::VARCHAR)
) AS rate_data(provider_code, send_currency_code, rate, note_en, note_ar)
  ON rate_data.provider_code = tp.code
WHERE eh.code = 'mig'
ON CONFLICT (exchange_provider_id, send_currency_code, receive_currency_code) DO UPDATE SET
    rate = EXCLUDED.rate,
    fee_type = EXCLUDED.fee_type,
    fee_value = EXCLUDED.fee_value,
    min_amount = EXCLUDED.min_amount,
    max_amount = EXCLUDED.max_amount,
    note_en = EXCLUDED.note_en,
    note_ar = EXCLUDED.note_ar,
    active = EXCLUDED.active,
    updated_at = NOW();

-- =============================================
-- EXCHANGE RECEIVE METHODS
-- Which local methods are available for payout for each exchange house.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.exchange_receive_methods (
    id                          BIGSERIAL    PRIMARY KEY,
    exchange_house_id           BIGINT       NOT NULL REFERENCES sarf.exchange_houses(id),
    transfer_method_id          BIGINT       NOT NULL REFERENCES sarf.transfer_methods(id),
    note_en                     VARCHAR(255),
    note_ar                     VARCHAR(255),
    requires_account_number     BOOLEAN      NOT NULL DEFAULT TRUE,
    requires_account_holder     BOOLEAN      NOT NULL DEFAULT TRUE,
    active                      BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order               INTEGER      NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_exchange_receive_method UNIQUE (exchange_house_id, transfer_method_id)
);

INSERT INTO sarf.exchange_receive_methods (
    exchange_house_id, transfer_method_id, note_en, note_ar,
    requires_account_number, requires_account_holder, active, display_order
)
SELECT
    eh.id,
    tm.id,
    CASE tm.code
        WHEN 'bank_transfer' THEN 'Account number and holder name are required.'
        ELSE NULL
    END,
    CASE tm.code
        WHEN 'bank_transfer' THEN 'رقم الحساب واسم صاحبه مطلوبان.'
        ELSE NULL
    END,
    TRUE,
    TRUE,
    TRUE,
    tm.display_order
FROM sarf.exchange_houses eh
JOIN sarf.transfer_methods tm
  ON tm.code IN ('bank_transfer', 'mobile_wallet')
WHERE eh.code = 'mig'
ON CONFLICT (exchange_house_id, transfer_method_id) DO UPDATE SET
    note_en = EXCLUDED.note_en,
    note_ar = EXCLUDED.note_ar,
    requires_account_number = EXCLUDED.requires_account_number,
    requires_account_holder = EXCLUDED.requires_account_holder,
    active = EXCLUDED.active,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();

-- =============================================
-- INTERNATIONAL KYC REQUIREMENTS
-- Dynamic KYC fields for international transfer.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.international_kyc_requirements (
    id                BIGSERIAL    PRIMARY KEY,
    exchange_house_id BIGINT       REFERENCES sarf.exchange_houses(id),
    provider_id       BIGINT       REFERENCES sarf.transfer_providers(id),
    field_code        VARCHAR(50)  NOT NULL,
    field_label_en    VARCHAR(100) NOT NULL,
    field_label_ar    VARCHAR(100) NOT NULL,
    field_type        VARCHAR(20)  NOT NULL CHECK (field_type IN ('TEXT', 'ATTACHMENT')),
    required          BOOLEAN      NOT NULL DEFAULT TRUE,
    allowed_mime_types TEXT[],
    display_order     INTEGER      NOT NULL DEFAULT 0,
    active            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_international_kyc_requirement_specific
    ON sarf.international_kyc_requirements (exchange_house_id, provider_id, field_code)
    WHERE provider_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_international_kyc_requirement_generic
    ON sarf.international_kyc_requirements (exchange_house_id, field_code)
    WHERE provider_id IS NULL;

INSERT INTO sarf.international_kyc_requirements (
    exchange_house_id, provider_id, field_code, field_label_en, field_label_ar,
    field_type, required, allowed_mime_types, display_order, active
)
SELECT
    eh.id,
    NULL,
    data.field_code,
    data.field_label_en,
    data.field_label_ar,
    data.field_type,
    TRUE,
    data.allowed_mime_types,
    data.display_order,
    TRUE
FROM sarf.exchange_houses eh
JOIN (
    VALUES
        ('sender_full_name', 'Sender full name', 'الاسم الكامل للمرسل', 'TEXT', NULL::TEXT[], 1),
        ('receiver_full_name', 'Receiver full name', 'الاسم الكامل للمستلم', 'TEXT', NULL::TEXT[], 2),
        ('id_document', 'ID document', 'وثيقة الهوية', 'ATTACHMENT', ARRAY['image/jpeg', 'image/png', 'application/pdf']::TEXT[], 3)
) AS data(field_code, field_label_en, field_label_ar, field_type, allowed_mime_types, display_order)
  ON TRUE
WHERE eh.code = 'mig'
AND NOT EXISTS (
    SELECT 1
    FROM sarf.international_kyc_requirements k
    WHERE k.exchange_house_id = eh.id
      AND k.provider_id IS NULL
      AND k.field_code = data.field_code
);

-- =============================================
-- TRANSFER QUOTES
-- Shared quote table for both internal and international transfer.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.transfer_quotes (
    quote_number            VARCHAR(36)    PRIMARY KEY,
    account_number          VARCHAR(6)     NOT NULL REFERENCES sarf.users(account_number),
    service_code            VARCHAR(50)    NOT NULL REFERENCES sarf.transfer_services(code),
    status                  VARCHAR(20)    NOT NULL CHECK (status IN ('ACTIVE', 'USED', 'EXPIRED', 'CANCELLED')),
    source_currency_code    VARCHAR(10)    NOT NULL REFERENCES sarf.currencies(code),
    target_currency_code    VARCHAR(10)    NOT NULL REFERENCES sarf.currencies(code),
    amount_sent             NUMERIC(18, 2) NOT NULL,
    applied_rate            NUMERIC(18, 6) NOT NULL,
    gross_amount            NUMERIC(18, 2) NOT NULL,
    fee_amount              NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_to_receive       NUMERIC(18, 2) NOT NULL,
    source_name_snapshot    VARCHAR(150),
    source_logo_url         VARCHAR(500),
    destination_name_snapshot VARCHAR(150),
    destination_logo_url    VARCHAR(500),
    payment_summary         VARCHAR(500),
    destination_summary     VARCHAR(500),
    expires_at              TIMESTAMP      NOT NULL,
    created_at              TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transfer_quotes_account
    ON sarf.transfer_quotes (account_number, created_at);

CREATE TABLE IF NOT EXISTS sarf.internal_transfer_quote_details (
    quote_number        VARCHAR(36) PRIMARY KEY REFERENCES sarf.transfer_quotes(quote_number) ON DELETE CASCADE,
    route_id            BIGINT      NOT NULL REFERENCES sarf.internal_transfer_routes(id),
    merchant_id         BIGINT      NOT NULL REFERENCES sarf.merchants(id),
    merchant_account_id BIGINT      NOT NULL REFERENCES sarf.merchant_accounts(id),
    source_method_id    BIGINT      NOT NULL REFERENCES sarf.transfer_methods(id),
    target_method_id    BIGINT      NOT NULL REFERENCES sarf.transfer_methods(id)
);

CREATE TABLE IF NOT EXISTS sarf.international_transfer_quote_details (
    quote_number            VARCHAR(36) PRIMARY KEY REFERENCES sarf.transfer_quotes(quote_number) ON DELETE CASCADE,
    exchange_house_id       BIGINT      NOT NULL REFERENCES sarf.exchange_houses(id),
    provider_id             BIGINT      NOT NULL REFERENCES sarf.transfer_providers(id),
    provider_rate_id        BIGINT      NOT NULL REFERENCES sarf.exchange_provider_rates(id),
    receive_method_id       BIGINT      REFERENCES sarf.transfer_methods(id),
    provider_reference_required BOOLEAN  NOT NULL DEFAULT TRUE
);

-- =============================================
-- TRANSFER ORDERS
-- Shared order table for both internal and international transfer.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.transfer_orders (
    order_number            VARCHAR(36)    PRIMARY KEY,
    quote_number            VARCHAR(36)    REFERENCES sarf.transfer_quotes(quote_number),
    account_number          VARCHAR(6)     NOT NULL REFERENCES sarf.users(account_number),
    service_code            VARCHAR(50)    NOT NULL REFERENCES sarf.transfer_services(code),
    status                  VARCHAR(30)    NOT NULL CHECK (status IN (
                                'PENDING_PAYMENT',
                                'RECEIPT_UPLOADED',
                                'SUBMITTED',
                                'UNDER_REVIEW',
                                'MORE_INFO_REQUIRED',
                                'READY_FOR_PAYOUT',
                                'COMPLETED',
                                'REJECTED',
                                'CANCELLED',
                                'EXPIRED'
                            )),
    source_currency_code    VARCHAR(10)    NOT NULL REFERENCES sarf.currencies(code),
    target_currency_code    VARCHAR(10)    NOT NULL REFERENCES sarf.currencies(code),
    amount_sent             NUMERIC(18, 2) NOT NULL,
    applied_rate            NUMERIC(18, 6) NOT NULL,
    gross_amount            NUMERIC(18, 2) NOT NULL,
    fee_amount              NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_to_receive       NUMERIC(18, 2) NOT NULL,
    source_name_snapshot    VARCHAR(150),
    source_logo_url         VARCHAR(500),
    destination_name_snapshot VARCHAR(150),
    destination_logo_url    VARCHAR(500),
    payment_summary         VARCHAR(500),
    destination_summary     VARCHAR(500),
    customer_reference      VARCHAR(100),
    notes                   VARCHAR(500),
    created_at              TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP      NOT NULL DEFAULT NOW(),
    submitted_at            TIMESTAMP      NOT NULL DEFAULT NOW(),
    reviewed_at             TIMESTAMP,
    completed_at            TIMESTAMP,
    cancelled_at            TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_transfer_orders_status
    ON sarf.transfer_orders (status, created_at);

CREATE INDEX IF NOT EXISTS idx_transfer_orders_account
    ON sarf.transfer_orders (account_number, created_at);

CREATE TABLE IF NOT EXISTS sarf.internal_transfer_order_details (
    order_number        VARCHAR(36) PRIMARY KEY REFERENCES sarf.transfer_orders(order_number) ON DELETE CASCADE,
    route_id            BIGINT      NOT NULL REFERENCES sarf.internal_transfer_routes(id),
    merchant_id         BIGINT      NOT NULL REFERENCES sarf.merchants(id),
    merchant_account_id BIGINT      NOT NULL REFERENCES sarf.merchant_accounts(id),
    source_method_id    BIGINT      NOT NULL REFERENCES sarf.transfer_methods(id),
    target_method_id    BIGINT      NOT NULL REFERENCES sarf.transfer_methods(id)
);

CREATE TABLE IF NOT EXISTS sarf.international_transfer_order_details (
    order_number                VARCHAR(36) PRIMARY KEY REFERENCES sarf.transfer_orders(order_number) ON DELETE CASCADE,
    exchange_house_id           BIGINT      NOT NULL REFERENCES sarf.exchange_houses(id),
    provider_id                 BIGINT      NOT NULL REFERENCES sarf.transfer_providers(id),
    provider_rate_id            BIGINT      NOT NULL REFERENCES sarf.exchange_provider_rates(id),
    receive_method_id           BIGINT      REFERENCES sarf.transfer_methods(id),
    provider_reference          VARCHAR(100),
    sender_full_name            VARCHAR(150) NOT NULL,
    receiver_full_name          VARCHAR(150) NOT NULL,
    destination_account_number  VARCHAR(100) NOT NULL,
    destination_account_holder  VARCHAR(150) NOT NULL,
    kyc_data_json               JSONB
);

-- =============================================
-- ORDER ATTACHMENTS
-- File metadata for receipts, KYC docs, payout proofs, etc.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.transfer_order_attachments (
    id                BIGSERIAL    PRIMARY KEY,
    order_number      VARCHAR(36)  NOT NULL REFERENCES sarf.transfer_orders(order_number) ON DELETE CASCADE,
    attachment_type   VARCHAR(30)  NOT NULL CHECK (attachment_type IN ('RECEIPT', 'KYC_DOCUMENT', 'PAYOUT_PROOF', 'OTHER')),
    label_en          VARCHAR(100),
    label_ar          VARCHAR(100),
    file_name         VARCHAR(255) NOT NULL,
    content_type      VARCHAR(100),
    storage_key       VARCHAR(500),
    preview_url       VARCHAR(500),
    file_data         BYTEA,
    uploaded_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transfer_order_attachments_order
    ON sarf.transfer_order_attachments (order_number, uploaded_at);

-- =============================================
-- ORDER STATUS HISTORY
-- Full audit trail for order lifecycle.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.transfer_order_status_history (
    id              BIGSERIAL   PRIMARY KEY,
    order_number    VARCHAR(36) NOT NULL REFERENCES sarf.transfer_orders(order_number) ON DELETE CASCADE,
    from_status     VARCHAR(30),
    to_status       VARCHAR(30) NOT NULL,
    actor_type      VARCHAR(30) NOT NULL CHECK (actor_type IN ('SYSTEM', 'USER', 'ADMIN', 'MERCHANT', 'EXCHANGE')),
    actor_reference VARCHAR(100),
    note            VARCHAR(500),
    created_at      TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transfer_order_status_history_order
    ON sarf.transfer_order_status_history (order_number, created_at);

-- =============================================
-- NOTIFICATIONS
-- Supports unread/read screens in the app.
-- =============================================
CREATE TABLE IF NOT EXISTS sarf.notifications (
    id              BIGSERIAL    PRIMARY KEY,
    account_number  VARCHAR(6)   NOT NULL REFERENCES sarf.users(account_number),
    category        VARCHAR(30)  NOT NULL CHECK (category IN ('TRANSFER', 'ACCOUNT', 'SECURITY', 'PROMOTION')),
    title_en        VARCHAR(255) NOT NULL,
    title_ar        VARCHAR(255) NOT NULL,
    content_en      VARCHAR(1000) NOT NULL,
    content_ar      VARCHAR(1000) NOT NULL,
    order_number    VARCHAR(36)  REFERENCES sarf.transfer_orders(order_number),
    is_read         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    read_at         TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_account_read
    ON sarf.notifications (account_number, is_read, created_at);

-- =============================================
-- ACCOUNT NUMBER GENERATOR FUNCTION
-- Returns a unique 6-digit numeric string.
-- =============================================
CREATE OR REPLACE FUNCTION sarf.generate_account_number()
RETURNS VARCHAR(6) AS $$
DECLARE
    new_account VARCHAR(6);
BEGIN
    LOOP
        new_account := (100000 + FLOOR(RANDOM() * 900000)::BIGINT)::TEXT;
        EXIT WHEN NOT EXISTS (
            SELECT 1
            FROM sarf.users
            WHERE account_number = new_account
        );
    END LOOP;

    RETURN new_account;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE sarf.users
    ALTER COLUMN account_number SET DEFAULT sarf.generate_account_number();
