// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7g5T1eXWKnB3NOHR9kpSsKRoKK761dQ',
    appId: '1:420777617459:web:0c63f6b9b02925928d1b46',
    messagingSenderId: '420777617459',
    projectId: 'sarf-54738',
    authDomain: 'sarf-54738.firebaseapp.com',
    storageBucket: 'sarf-54738.firebasestorage.app',
    measurementId: 'G-Z1YWP5Q293',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwXKAr6S-ZTjrPSrOkktmg3MvOcS_1cZY',
    appId: '1:420777617459:android:073297912e0266af8d1b46',
    messagingSenderId: '420777617459',
    projectId: 'sarf-54738',
    storageBucket: 'sarf-54738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGvAqo5BpsQeYrI9yj7iz3_EeCKhdqUk',
    appId: '1:420777617459:ios:16bb976e19e7861e8d1b46',
    messagingSenderId: '420777617459',
    projectId: 'sarf-54738',
    storageBucket: 'sarf-54738.firebasestorage.app',
    iosBundleId: 'com.sarf.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGvAqo5BpsQeYrI9yj7iz3_EeCKhdqUk',
    appId: '1:420777617459:ios:16bb976e19e7861e8d1b46',
    messagingSenderId: '420777617459',
    projectId: 'sarf-54738',
    storageBucket: 'sarf-54738.firebasestorage.app',
    iosBundleId: 'com.sarf.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7g5T1eXWKnB3NOHR9kpSsKRoKK761dQ',
    appId: '1:420777617459:web:7723dadca98f5fbd8d1b46',
    messagingSenderId: '420777617459',
    projectId: 'sarf-54738',
    authDomain: 'sarf-54738.firebaseapp.com',
    storageBucket: 'sarf-54738.firebasestorage.app',
    measurementId: 'G-RCH8F4FFS6',
  );
}
